# Generated by Django 3.2.25 on 2024-09-01 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 1, 9, 16, 44, 611644))),
                ('end_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 1, 9, 16, 44, 611644))),
                ('end_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('cls', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='secondapp.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
