# Generated by Django 3.2.25 on 2024-09-06 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
